### ISSUE TITLE
cli img not booting

### ISSUE THREAD

**Issue by wrossi** [radxa-build/radxa-zero3#5] opened 2024-01-26 17:29 UTC
is there any cli image working? I tried b4,b5,b6 but they all get stuck at roofs clean

**Comment by danielfaust** [comment] 2024-01-27 21:11
Can confirm, none of the cli images boot (also not Ubuntu). At least not on Zero 3E.

**Comment by RadxaYuntian** [comment] 2024-01-29 06:20
Duplicate of #4

**Closed by RadxaYuntian** 2024-01-29 06:20 UTC

**Comment by wrossi** [comment] 2024-01-29 09:24
yep - I only have 3W boards, and none of the cli img boot. Ubuntu img seems to blink more but no video output.
