### ISSUE TITLE
wifi not available in radxa-zero3_debian_bullseye_xfce_b3 image

### ISSUE THREAD

**Issue by tester58126** [radxa-build/radxa-zero3#3] opened 2023-12-29 12:28 UTC
When dmesg command, wifi appears to be ap6212

but ap6212 does not support wifi 6

Even if I remove the radxa sticker on the zero 3w wifi chip that I received today, nothing is written on it

What is the exact wifi chip name and how to work it

**Comment by tester58126** [comment] 2023-12-29 13:26
Is there an image that works normally

**Comment by tester58126** [comment] 2023-12-29 20:08
![화면 캡처 2023-12-30 050449](https://github.com/radxa-build/radxa-zero3/assets/94805997/f8829d00-e83c-45ea-85bc-fe3424251b9f)
After executing the above command, it works now, but why are the officially provided images not working properly by default?

**Comment by zehnm** [comment] 2023-12-31 10:35
Same issue here: WiFi and Bluetooth don't work in the `radxa-zero3_debian_bullseye_cli_b3.img` image!
I've also done the system update with a USB network adapter and got a broken system because of conflicting radxa packages dependencies between `task-radxa-zero3`, `radxa-system-config-kernel-cmdline-ttyfiq0` and `radxa-system-config-common` 👎 
After some hammering with removing `task-radxa-zero3`, fix-upgrade and re-installing it, it finally resolved.
  
Afterwards the WiFi device finally showed up, but I can't connect to my access point (WPA2 personal security). Yes, password is 100% correct.
Logs only show:
```
[  152.500633] debugfs: Directory '18:e8:29:68:df:bd' with parent 'rc' already present!
[  152.500727] aicwf_sdio mmc2:390b:1: Error while (un)registering debug entry for sta 6
```

Other question: what's the deal with eth0 spamming the logs and the constant desktop popups? There is no ethernet on this board. I found a disable option in rsetup, but this doesn't work either. These log entries are continuously created:
```
[   20.943085] rk_gmac-dwmac fe010000.ethernet: Failed to reset the dma
[   20.943148] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   20.943162] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_open: Hw setup failed
[   22.210582] rk_gmac-dwmac fe010000.ethernet: Failed to reset the dma
[   22.210687] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   22.210704] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_open: Hw setup failed
[   23.318182] rk_gmac-dwmac fe010000.ethernet: Failed to reset the dma
[   23.318244] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   23.318257] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_open: Hw setup failed
[   24.436248] rk_gmac-dwmac fe010000.ethernet: Failed to reset the dma
[   24.436340] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   24.436357] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_open: Hw setup failed
[   25.747360] rk_gmac-dwmac fe010000.ethernet: Failed to reset the dma
[   25.747419] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   25.747433] rk_gmac-dwmac fe010000.ethernet eth0: stmmac_open: Hw setup failed
```

Please provide a working image and missing documentation in https://docs.radxa.com/en/zero/zero3, starting with the correct username and password in https://docs.radxa.com/en/zero/zero3/radxa-os ;-) It's just `rock` and NOT `radxa/rock`

**Comment by zehnm** [comment] 2023-12-31 14:34
More information about WiFi issues:
- Connecting to a mixed 2.4 / 5 GHz network doesn't work.
- Connecting to another, 2.4 GHz network only on the same AP with WPA2 personal worked!
- AP is a UniFi UAP AC Pro
- WiFi country was set with rsetup before trying to connect (rsetup: Localization -> Change Wi-Fi Country)
- Same issue if trying to connect on the desktop or CLI with `sudo nmcli device wifi connect <ssid> password <passwd>`
- System date & time is accurate

Kernel logs:
```
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        >>> rwnx_cfg80211_scan()
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        >>> rwnx_send_scanu_req()
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_send_msg (4104)SCANU_VENDOR_IE_CFM reqcfm:1 in_irq:0 in_softirq:0 in_atomic:0
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_cmd_malloc get cmd_array[0]:00000000354f4802 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_cmd_free cmd_array[0]:00000000354f4802 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:1(2412) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:2(2417) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:3(2422) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:4(2427) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:5(2432) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:6(2437) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:7(2442) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:8(2447) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:9(2452) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:10(2457) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:11(2462) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:12(2467) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:13(2472) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:14(2484) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:36(5180) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:40(5200) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:44(5220) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:48(5240) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:52(5260) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:56(5280) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:60(5300) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:64(5320) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:100(5500) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:104(5520) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:108(5540) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:112(5560) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:116(5580) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:120(5600) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:124(5620) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:128(5640) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:132(5660) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:136(5680) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:140(5700) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:144(5720) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:149(5745) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:153(5765) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:157(5785) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:161(5805) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGDEBUG)        scan channel:165(5825) 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_send_msg (4105)SCANU_START_CFM_ADDTIONAL reqcfm:1 in_irq:0 in_softirq:0 in_atomic:0
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_cmd_malloc get cmd_array[0]:00000000354f4802 
Dec 31 15:01:10 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_cmd_free cmd_array[0]:00000000354f4802 
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        >>> rwnx_rx_scanu_start_cfm()
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: wlan0: CTRL-EVENT-SSID-REENABLED id=0 ssid="IOT Net"
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: wlan0: Trying to associate with 18:e8:29:68:df:bd (SSID='IOT Net' freq=5180 MHz)
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        >>> rwnx_cfg80211_connect()
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        >>> rwnx_send_sm_connect_req()
Dec 31 15:01:11 radxa-zero3 kernel: rwnx_send_sm_connect_req drv_vif_index:0 connect to IOT Net(10) channel:5180 auth_type:0
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_send_msg (6145)SM_CONNECT_CFM reqcfm:1 in_irq:0 in_softirq:0 in_atomic:0
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_cmd_malloc get cmd_array[0]:00000000354f4802 
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        rwnx_cmd_free cmd_array[0]:00000000354f4802 
Dec 31 15:01:11 radxa-zero3 NetworkManager[339]: <info>  [1704031271.7300] device (wlan0): supplicant interface state: scanning -> associating
Dec 31 15:01:11 radxa-zero3 NetworkManager[339]: <info>  [1704031271.7304] device (p2p-dev-wlan0): supplicant management interface state: scanning -> associating
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        >>> rwnx_rx_sm_connect_ind()
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGINFO)        rwnx_rx_sm_connect_ind ind->status_code:0 
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGINFO)        rwnx_rx_sm_connect_ind ind->roamed:0 ind->status_code:0 rwnx_vif->drv_conn_state:2
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGINFO)        rwnx_rx_sm_connect_ind cfg80211_connect_result pass 
Dec 31 15:01:11 radxa-zero3 kernel: debugfs: Directory '18:e8:29:68:df:bd' with parent 'rc' already present!
Dec 31 15:01:11 radxa-zero3 kernel: aicwf_sdio mmc2:390b:1: Error while (un)registering debug entry for sta 12
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        >>> rwnx_rx_sm_disconnect_ind()
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGTRACE)        >>> rwnx_cfg80211_unlink_bss()
Dec 31 15:01:11 radxa-zero3 kernel: AICWFDBG(LOGINFO)        rwnx_cfg80211_unlink_bss(): cfg80211_unlink IOT Net!!
Dec 31 15:01:11 radxa-zero3 kernel: deinit:macaddr:98,3,cf,c6,e3,ae
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: wlan0: Associated with 18:e8:29:68:df:bd
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: wlan0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: wlan0: CTRL-EVENT-REGDOM-CHANGE init=COUNTRY_IE type=COUNTRY alpha2=CH
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: wlan0: CTRL-EVENT-DISCONNECTED bssid=18:e8:29:68:df:bd reason=2
Dec 31 15:01:11 radxa-zero3 NetworkManager[339]: <info>  [1704031271.9836] device (wlan0): supplicant interface state: associating -> associated
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: BSSID 18:e8:29:68:df:bd ignore list count incremented to 3, ignoring for 60 seconds
Dec 31 15:01:11 radxa-zero3 NetworkManager[339]: <info>  [1704031271.9840] device (p2p-dev-wlan0): supplicant management interface state: associating -> associated
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="IOT Net" auth_failures=2 duration=20 reason=CONN_FAILED
Dec 31 15:01:11 radxa-zero3 wpa_supplicant[373]: wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
Dec 31 15:01:11 radxa-zero3 NetworkManager[339]: <info>  [1704031271.9930] device (wlan0): supplicant interface state: associated -> disconnected
Dec 31 15:01:11 radxa-zero3 NetworkManager[339]: <info>  [1704031271.9935] device (p2p-dev-wlan0): supplicant management interface state: associated -> disconnected
```

Issue: `wlan0: CTRL-EVENT-DISCONNECTED bssid=18:e8:29:68:df:bd reason=2`

Googling for `CTRL-EVENT-DISCONNECTED reason=2`:
- [reveals "Previous authentication no longer valid"](https://www.toomanyatoms.com/computer/disconnection_codes.html).
- According to [this report](https://raspberrypi.stackexchange.com/questions/105639/wpa-supplicant-instantly-drops-eap-connection-citing-reason-2) it seems to be a bug related with the nl80211 driver or wpa_supplicant.

**Comment by RadxaYuntian** [comment] 2024-01-02 04:00
We have upgraded the Wi-Fi module used on 3W, which is not supported in the current release (b3). We have found an issue in the RC image b4 where 2.4G Wi-Fi and Bluetooth cannot coexist. A workaround is already available, and we will create a image soon with this fix.

**Comment by zehnm** [comment] 2024-01-02 11:55
> We have upgraded the Wi-Fi module used on 3W, which is not supported in the current release (b3).

Then please make the b4 image the officially recommended image for now, with setting the `latest` tag to b4. Otherwise users will just fall into the same trap and don't have working WiFi.

> We have found an issue in the RC image b4 where 2.4G Wi-Fi and Bluetooth cannot coexist.

I'll patiently await your new image and then test again.
Please also test with 5 GHz WiFi networks, this is currently not working for me, also with the b4 image.

**Comment by warpme** [comment] 2024-01-08 10:33
> We have found an issue in the RC image b4 where 2.4G Wi-Fi and Bluetooth cannot coexist. A workaround is already available

May you pls point me to aix8800 sources where this workaround is applied?

**Comment by tester58126** [comment] 2024-01-08 11:12
> > RC 이미지 b4에서 2.4G Wi-Fi와 Bluetooth가 공존할 수 없는 문제가 발견되었습니다. 해결 방법은 이미 사용할 수 있습니다
> 
> 이 해결 방법이 적용되는 aix8800 소스를 알려주시겠습니까?

https://github.com/radxa-pkg/aic8800

**Comment by RadxaYuntian** [comment] 2024-01-08 11:23
> May you pls point me to aix8800 sources where this workaround is applied?

You will also need [a script to reset the Bluetooth controller](https://github.com/radxa-pkg/rsetup/blob/main/src/usr/lib/rsetup/mod/aic8800.sh) and [Systemd services](https://github.com/radxa-pkg/rsetup/blob/main/debian/rsetup.rsetup-aic8800-reset%40.service) to [attach the Bluetooth HCI](https://github.com/radxa-pkg/rsetup/blob/main/debian/rsetup.rsetup-hciattach%40.service). The serial device for Bluetooth is [ttyS1](https://github.com/radxa-pkg/rsetup/blob/main/config/00-aic8800-reset-ttys1.conf).

All of those are already implemented in our system. We are currently waiting for https://github.com/radxa-pkg/rsetup/pull/28 to complete before we can prepare the next image.

**Comment by warpme** [comment] 2024-01-08 12:34
@RadxaYuntian 
Thx for hints!
Does v2023_1212_15dcf017 of aic8800 drivers/firmware addressing issue: mixed 2.4 / 5 GHz network doesn't work?

**Comment by RadxaYuntian** [comment] 2024-01-08 12:41
I'm not aware of this issue. Maybe you are using WPA3?

**Comment by warpme** [comment] 2024-01-08 12:44
Oh - i'm only referring to https://github.com/radxa-build/radxa-zero3/issues/3#issuecomment-1872963461 in this ticket...

**Comment by zehnm** [comment] 2024-01-08 12:45
> I'm not aware of this issue. Maybe you are using WPA3?

See my comment above: https://github.com/radxa-build/radxa-zero3/issues/3#issuecomment-1872963461
Additional information: it's mixed WPA2/WPA3 personal. All my other IOT devices have no issues connecting to this network.
Let me know if you need more information.

**Comment by RadxaYuntian** [comment] 2024-01-08 12:45
By mixed 2.4G & 5G I assume you mean they share the same SSID. Then I don't think we have tested this before.

**Comment by RadxaYuntian** [comment] 2024-01-08 12:49
Regardless I think the issue is still WPA3. It has been an issue for us to support WPA3 on Debian 11

**Comment by zehnm** [comment] 2024-01-08 12:59
> By mixed 2.4G & 5G I assume you mean they share the same SSID. Then I don't think we have tested this before.

Yes. Usually this is the default setup from what I've seen in quite a few access points.

> Regardless I think the issue is still WPA3. It has been an issue for us to support WPA3 on Debian 11

Then it should fallback to WPA2, it's not a WPA3-only setup :-)
Please see the included link, it could be an issue with the nl80211 driver or wpa_supplicant.

**Comment by RadxaYuntian** [comment] 2024-01-09 02:17
I know but fallback does not work properly, which is why WPA3 needs to be disabled.

**Comment by WillJBrown** [comment] 2024-03-03 14:13
I'm having the same issue still on b6 with a WPA2 network. Any news on this?

**Comment by RadxaYuntian** [comment] 2024-03-04 07:03
I'll close this issue since with b6 release, the original issue is now fixed.

@WillJBrown please send an email to support@radxa.com, and provide your wireless module model to us. We will check what was wrong for you.

**Closed by RadxaYuntian** 2024-03-04 07:03 UTC

**Comment by platima** [comment] 2024-03-30 23:26
Yeah even with b6 there are still massive wifi issues.

New Zero 3W, Debian 11 XFCE image (b6), Wifi 6 WPA2, connects and I can ping IPs and hostnames, so data is working, but there is not enough throughput for anything, eg cannot `apt-get update` or access a web page. As soon as I connect USB LAN it's fine.

Interface information shows speed unknown, but signal looks strong. Other devices next to it work fine.

**Comment by platima** [comment] 2024-03-31 00:16
Through trial and error disabling antennas, trying different networks, etc, I found mixed 2.4/5GHz did not work. I connected to a 2.4-only network and it's fine.

Updating to https://github.com/radxa-pkg/aic8800/releases/tag/3.0%2Bgit20240116.ec460377-4 did not help - actually had no wifi at all after installing it.

**Comment by RadxaYuntian** [comment] 2024-04-01 02:37
You have to update both Wi-Fi driver as well as matching Wi-Fi firmware, which is provided in [radxa-firmware](https://github.com/radxa-pkg/radxa-firmware). The 2 must match.

**Comment by platima** [comment] 2024-04-01 02:44
Hey yeah I figured that, but just found in the end that with latest buidl radxa-zero3_debian_bullseye_cli_b6.img.xz;
 - WPA3 does not work
 - 5GHz connects but minimal traffic
Have to connect LAN

I'm publishing a video today on @PlatimaTinkers about this, and pushing out some updated Armbian builds with fixed wifi and fixed hardware accelerated graphics at https://github.com/platima/sbc-images
